import "server-only"

// Central AI config — one place to swap model, tune privacy, and set cost guards.
// The model is reached through the Vercel AI SDK, so switching providers is a
// localized change (this file + the provider import in service.ts), nothing else.

/** Gemini model for report insights. Free-tier eligible; change here to swap. */
export const AI_MODEL = "gemini-2.5-flash"

/** Human label for the model, surfaced in the UI ("Generated by …"). */
export const AI_MODEL_LABEL = "Gemini 2.5 Flash"

/**
 * Privacy mode for the data handed to the model:
 *   - "aggregate" — only totals/counts leave the server; no student names. (default)
 *   - "detailed" — names + per-student figures (richer answers). Flip with care:
 *     this is minors' PII leaving to a third-party API.
 * The data layer reads this to decide what to include in the snapshot.
 */
export const AI_PRIVACY_MODE: "aggregate" | "detailed" = "aggregate"

/** True once a Gemini API key is present — gates generation with a clear error. */
export function isAiConfigured(): boolean {
  return Boolean(process.env.GOOGLE_GENERATIVE_AI_API_KEY)
}
