// Shared AI feature types. Kept framework-free so both the server service and
// the client components/hooks can import them.

export type InsightTone = "positive" | "attention" | "neutral"

export type Insight = {
  /** Short label, a few words. */
  title: string
  /** One or two sentences citing the snapshot's numbers. */
  detail: string
  tone: InsightTone
}

/** What the insights endpoint returns to the client. */
export type InsightResult = {
  headline: string
  insights: Insight[]
  /** ISO timestamp of when this set was generated. */
  generatedAt: string
  /** Model label, for the "Generated by" footnote. */
  model: string
  /** True when served from the daily cache rather than freshly generated. */
  cached: boolean
}

// ─── The snapshot handed to the model (anonymized in aggregate mode) ───────────

export type AttendanceSnapshot = {
  date: string
  present: number
  absent: number
  leave: number
  notMarked: number
}

export type FinanceTrendPoint = {
  /** Display label, e.g. "Jun 2026". */
  month: string
  collected: number
  expected: number
}

export type FinanceSnapshot = {
  month: string
  collected: number
  expected: number
  outstanding: number
  waived: number
  paidStudents: number
  pendingStudents: number
  /** Recent months, oldest → newest, for month-on-month movement. */
  trend: FinanceTrendPoint[]
}

export type InstituteSnapshot = {
  instituteName: string
  currency: string
  activeStudents: number
  attendance: AttendanceSnapshot
  /** null when the viewer lacks fee:read — financial data is never fetched. */
  finance: FinanceSnapshot | null
}
