"use client"

import { AlertCircle, RefreshCw, Sparkles } from "lucide-react"

import { cn } from "@/lib/utils"
import { formatRelative } from "@/lib/date-helper"
import { ApiError } from "@/lib/http"
import { useInsights, useRegenerateInsights } from "../hooks"
import type { InsightTone } from "../types"

const TONE_DOT: Record<InsightTone, string> = {
  positive: "bg-emerald-500",
  attention: "bg-amber-500",
  neutral: "bg-foreground/25",
}

export function InsightsCard() {
  const { data, isLoading, error } = useInsights()
  const regenerate = useRegenerateInsights()
  const busy = isLoading || regenerate.isPending

  return (
    <section className="card-soft bg-card rounded-[16px] p-5">
      <div className="mb-4 flex items-center justify-between gap-3">
        <h2 className="flex items-center gap-2 font-semibold">
          <Sparkles className="size-4 text-violet-500" />
          AI insights
        </h2>
        <button
          type="button"
          onClick={() => regenerate.mutate()}
          disabled={busy}
          className="text-muted-foreground hover:text-foreground inline-flex items-center gap-1.5 text-xs font-medium transition-colors disabled:opacity-50"
        >
          <RefreshCw className={cn("size-3.5", busy && "animate-spin")} />
          Regenerate
        </button>
      </div>

      {isLoading ? (
        <InsightsSkeleton />
      ) : error ? (
        <InsightsError error={error} />
      ) : data ? (
        <div className="space-y-4">
          <p className="text-sm leading-relaxed font-medium">{data.headline}</p>
          <ul className="divide-border/60 divide-y">
            {data.insights.map((it, i) => (
              <li key={i} className="flex gap-3 py-3 first:pt-0 last:pb-0">
                <span
                  className={cn("mt-1.5 size-2 shrink-0 rounded-full", TONE_DOT[it.tone])}
                  aria-hidden
                />
                <div className="space-y-0.5">
                  <p className="text-sm font-medium">{it.title}</p>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {it.detail}
                  </p>
                </div>
              </li>
            ))}
          </ul>
          <p className="text-muted-foreground/80 text-[11px]">
            Generated by {data.model} · {formatRelative(data.generatedAt)}
          </p>
        </div>
      ) : null}
    </section>
  )
}

function InsightsError({ error }: { error: unknown }) {
  const message =
    error instanceof ApiError ? error.message : "Couldn't load insights right now."
  return (
    <div className="bg-muted/50 flex items-start gap-3 rounded-[12px] p-4">
      <AlertCircle className="text-muted-foreground mt-0.5 size-4 shrink-0" />
      <p className="text-muted-foreground text-sm">{message}</p>
    </div>
  )
}

function InsightsSkeleton() {
  return (
    <div className="space-y-4">
      <div className="bg-muted h-4 w-3/4 animate-pulse rounded" />
      {[0, 1, 2].map((i) => (
        <div key={i} className="space-y-1.5">
          <div className="bg-muted h-3.5 w-1/3 animate-pulse rounded" />
          <div className="bg-muted h-3.5 w-full animate-pulse rounded" />
        </div>
      ))}
    </div>
  )
}
